ARG ROOT_CONTAINER=registry.gitlab.bsc.es/ppc/software/compss/conn-ubuntu-base:3.3-amd
FROM $ROOT_CONTAINER

ARG ARCH=amd64
ARG FULL_ARCH=x86_64
ARG release=false

# Copy framework files for installation and testing
COPY . /framework

ENV GRADLE_HOME /opt/gradle
ENV JAVA_HOME /usr/lib/jvm/java-8-openjdk-${ARCH}/

ENV EXTRAE_MPI_HEADERS /usr/include/${FULL_ARCH}-linux-gnu/mpi
ENV PATH $PATH:/opt/COMPSs/Runtime/scripts/user:/opt/COMPSs/Bindings/c/bin:/opt/COMPSs/Runtime/scripts/utils:/opt/gradle/bin
ENV CLASSPATH $CLASSPATH:/opt/COMPSs/Runtime/compss-engine.jar
ENV LD_LIBRARY_PATH /opt/COMPSs/Bindings/bindings-common/lib:$JAVA_HOME/jre/lib/${ARCH}/server
ENV COMPSS_HOME=/opt/COMPSs

# Install COMPSs
RUN cd /framework && \
    apt update -y && apt install git -y \
    && export EXTRAE_MPI_HEADERS=/usr/include/${FULL_ARCH}-linux-gnu/mpi \
    && /framework/submodules_get.sh \
    && /framework/builders/buildlocal -S /opt/COMPSs/ \
    && mv /root/.m2 /home/jenkins \
    && chown -R jenkins: /framework \
    && chown -R jenkins: /home/jenkins/

# Expose SSH port and run SSHD (if needed)
EXPOSE 22
CMD ["/usr/sbin/sshd","-D"]
